wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.10
    cli_version: 0.17.8
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1740055314
    t:
      1:
      - 2
      - 3
      - 30
      - 49
      - 51
      - 55
      2:
      - 2
      - 3
      - 30
      - 49
      - 51
      - 55
      3:
      - 13
      - 23
      - 61
      4: 3.11.10
      5: 0.17.8
      8:
      - 5
      13: darwin-x86_64
